# ECE 2112: Advanced Computer Programming and Algorithms
## Experiment 2: Numerical Python (NumPy)

**Name:** Herrera, Adrian Joseph R.  
**Section:** 2ECE-D  
**Date Submitted:** August 27, 2026

### Problem A: Reproducible Matrix Normalization

**Approach:**
We set a random seed using `np.random.seed(2112)` to guarantee reproducible pseudo-random matrix generation. Using a 5x5 random array $X$, we calculate the overall mean ($\mu$) and standard deviation ($\sigma$). The array is normalized via standard score transformation $Z = \frac{X - \mu}{\sigma}$ and exported as a binary `.npy` file.

In [12]:
import numpy as np

# Set seed for reproducible random generation
np.random.seed(2112)

# Generate 5x5 array of uniform random floats in [0, 1)
X = np.random.rand(5, 5)

# Calculate matrix statistics
mean = X.mean()
std = X.std()

# Apply standard score normalization
X_normalized = (X - mean) / std

# Export normalized array to binary format
np.save("X_normalized.npy", X_normalized)

# --- Output Verification ---
print("Mean:", mean)
print("Standard Deviation:", std)
print("\nNormalized Matrix:\n", X_normalized)

Mean: 0.5095952417252493
Standard Deviation: 0.24958904141692517

Normalized Matrix:
 [[-1.68998816 -1.44521549  0.19381725  0.44350683  0.87690428]
 [-1.63992242  0.02782114 -0.20020108 -0.29806592 -0.42445617]
 [ 0.26377396  1.35561225  0.26784202 -1.04929505  1.84325072]
 [-0.02482825  0.59385181 -1.51641926 -1.67372345  1.31016644]
 [ 0.01494401  0.43278433  0.31421219  0.82368211  1.19994591]]


### Problem B: Cubes Divisible by 4

**Approach:**
We generate an array of the first 100 positive integers ($1$ to $100$) using `np.arange`, reshape it into a 10x10 matrix, and compute the element-wise cube ($x^3$). A Boolean mask evaluates elements where $x^3 \pmod 4 == 0$ to isolate divisible terms into a 1D array before saving to disk.

In [13]:
# Generate 10x10 grid of integers 1 through 100
arr = np.arange(1, 101).reshape(10, 10)

# Vectorized element-wise cubing
cubed_arr = arr ** 3

# Boolean filtering for divisibility by 4
div_by_4 = cubed_arr[cubed_arr % 4 == 0]

# Export filtered array
np.save("div_by_4.npy", div_by_4)

# --- Output Verification ---
print("Shape of filtered array:", div_by_4.shape)
print("First 10 elements divisible by 4:\n", div_by_4[:10])

Shape of filtered array: (50,)
First 10 elements divisible by 4:
 [   8   64  216  512 1000 1728 2744 4096 5832 8000]


### Problem C: Above-Mean Squares

**Approach:**
We create a 6x6 matrix of squared positive integers ($1^2$ to $36^2$). After computing the scalar mean of the matrix, relational comparison (`> mean`) extracts all elements strictly greater than the overall average. The filtered array is saved as a binary output.

In [14]:
# Create 6x6 matrix of consecutive integers squared
arr_seq = np.arange(1, 37).reshape(6, 6)
squared_arr = arr_seq ** 2

# Compute scalar mean of all elements
matrix_mean = squared_arr.mean()

# Relational Boolean masking
above_mean = squared_arr[squared_arr > matrix_mean]

# Export result to binary format
np.save("above_mean.npy", above_mean)

# --- Output Verification ---
print("Matrix Mean:", matrix_mean)
print("Elements above mean:\n", above_mean)

Matrix Mean: 450.1666666666667
Elements above mean:
 [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
