# ECE 2112: Advanced Computer Programming and Algorithms
## Experiment 2: Numerical Python (NumPy)

**Name:** Herrera, Adrian Joseph R.  
**Section:** 2ECE-D  
**Date Submitted:** August 27, 2026

### Problem A: Reproducible Matrix Normalization

**Approach:**
We set a random seed using `np.random.seed(2112)` to guarantee reproducible pseudo-random matrix generation. Using a 5x5 random array $X$, we calculate the overall mean ($\mu$) and standard deviation ($\sigma$). The array is normalized via standard score transformation $Z = \frac{X - \mu}{\sigma}$ and exported as a binary `.npy` file.

In [12]:
import numpy as np

# Set seed for reproducible random generation
np.random.seed(2112)

# Generate 5x5 array of uniform random floats in [0, 1)
X = np.random.rand(5, 5)

# Calculate matrix statistics
mean = X.mean()
std = X.std()

# Apply standard score normalization
X_normalized = (X - mean) / std

# Export normalized array to binary format
np.save("X_normalized.npy", X_normalized)

# --- Output Verification ---
print("Mean:", mean)
print("Standard Deviation:", std)
print("\nNormalized Matrix:\n", X_normalized)

Mean: 0.5095952417252493
Standard Deviation: 0.24958904141692517

Normalized Matrix:
 [[-1.68998816 -1.44521549  0.19381725  0.44350683  0.87690428]
 [-1.63992242  0.02782114 -0.20020108 -0.29806592 -0.42445617]
 [ 0.26377396  1.35561225  0.26784202 -1.04929505  1.84325072]
 [-0.02482825  0.59385181 -1.51641926 -1.67372345  1.31016644]
 [ 0.01494401  0.43278433  0.31421219  0.82368211  1.19994591]]
